/*
* generated by Xtext
*/
package org.pklose.simplespec.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SimplespecOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
