/*
 * generated by Xtext
 */
package org.pklose.simplespec;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SimplespecUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.pklose.simplespec.ui.internal.SimplespecActivator.getInstance().getInjector("org.pklose.simplespec.Simplespec");
	}
	
}
