/*
 * generated by Xtext
 */
package org.pklose.simplespec;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SimplespecRuntimeModule extends org.pklose.simplespec.AbstractSimplespecRuntimeModule {

}
