/*
 * generated by Xtext
 */
package org.pklose.simplespec.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractSimplespecJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.pklose.simplespec.simplespec.SimplespecPackage.eINSTANCE);
		return result;
	}

}
