/*
 * generated by Xtext
 */
package org.pklose.simplespec.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.pklose.simplespec.ui.internal.SimplespecActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimplespecExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimplespecActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimplespecActivator.getInstance().getInjector(SimplespecActivator.ORG_PKLOSE_SIMPLESPEC_SIMPLESPEC);
	}
	
}
