/*
 * generated by Xtext
 */
package org.pklose.simplespec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimplespecUiModule extends org.pklose.simplespec.ui.AbstractSimplespecUiModule {
	public SimplespecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
