/*
* generated by Xtext
*/
package org.pklose.simplespec.ui.contentassist;

import org.pklose.simplespec.ui.contentassist.AbstractSimplespecProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SimplespecProposalProvider extends AbstractSimplespecProposalProvider {

}
