/*
 * generated by Xtext
 */
package org.pklose.simplespec.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.pklose.simplespec.services.SimplespecGrammarAccess;

public class SimplespecParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SimplespecGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.pklose.simplespec.parser.antlr.internal.InternalSimplespecParser createParser(XtextTokenStream stream) {
		return new org.pklose.simplespec.parser.antlr.internal.InternalSimplespecParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public SimplespecGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimplespecGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
