/*
 * generated by Xtext
 */
package org.pklose.simplespec.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimplespecAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/pklose/simplespec/parser/antlr/internal/InternalSimplespec.tokens");
	}
}
